name: Notificaci贸n a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Enviar notificaci贸n a ntfy.sh
        run: |
          curl -H "Title: Push a main" \
               -H "Priority: high" \
               -d "C贸digo subido a main en HolaMundoCI" \
               https://ntfy.sh/devops-itla
